Repository prgrms-web-devcourse/Team_Coco_FE, pull requests merged in 2021-12, with the labels that each got.

#2 feat: 랜딩 페이지 구현
  src/components/Layout/PrivatePageLayout.tsx
  src/components/Layout/PublicPageLayout.tsx
  src/components/Layout/index.ts
  src/components/Logo/Logo.tsx
  src/components/Logo/index.ts
  src/pages/auth/LandingPage.tsx
  src/pages/auth/index.ts
  src/pages/posts/PostsPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/pages/schedules/SchedulesPage.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#5 feat: 라우팅 페이지 설정
  src/components/BottomNavigation/BottomNavigation.tsx
  src/components/BottomNavigation/useBottomNavigation.ts
  src/features/posts/components/Post/Post.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/RegisterPage.tsx
  src/pages/auth/index.ts
  src/pages/index.ts
  src/pages/memo/MemoPage.tsx
  src/pages/memo/MemoUpdatePage.tsx
  src/pages/memo/index.ts
  src/pages/note/NotePage.tsx
  src/pages/note/index.ts
  src/pages/posts/PostPage.tsx
  src/pages/posts/PostUpdatePage.tsx
  src/pages/posts/PostsPage.tsx
  src/pages/posts/index.ts
  src/pages/schedules/SchedulePage.tsx
  src/pages/schedules/ScheduleUpdatePage.tsx
  src/pages/schedules/SchedulesPage.tsx
  src/pages/schedules/index.ts
  src/pages/vote/VotePage.tsx
  src/pages/vote/VoteUpdatePage.tsx
  src/pages/vote/index.ts
  src/routes/index.tsx
  src/routes/memo/index.tsx
  src/routes/note/index.tsx
  src/routes/posts/index.tsx
  src/routes/schedules/index.tsx
  src/routes/vote/index.tsx
Labels: ✨ Feature

#8 feat: 로그인 페이지 및 회원가입 페이지 구현
  src/components/Logo/Logo.tsx
  src/features/auth/components/LoginForm/LoginForm.tsx
  src/features/auth/components/LoginForm/index.ts
  src/features/auth/components/RegisterForm/RegisterForm.tsx
  src/features/auth/components/RegisterForm/index.ts
  src/features/auth/components/index.ts
  src/pages/auth/LandingPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/RegisterPage.tsx
Labels: ✨ Feature

#9 feat: Schedules 생성 페이지 markup
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  package.json
  public/index.html
  src/components/CustomizedModal/CustomizedModal.tsx
  src/components/CustomizedModal/index.ts
  src/features/schedules/components/AddSchedule/AddSchedule.tsx
  src/features/schedules/components/AddSchedule/index.ts
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/AddSchleduleForm/index.ts
  src/features/schedules/components/Daily/Daily.tsx
  src/features/schedules/components/Daily/index.ts
  src/features/schedules/components/Dailys/Dailys.tsx
  src/features/schedules/components/Dailys/index.ts
  src/features/schedules/components/FriendsList/FriendsList.tsx
  src/features/schedules/components/FriendsList/index.ts
  src/features/schedules/components/MapContainer/MapContainer.tsx
  src/features/schedules/components/MapContainer/index.ts
  src/features/schedules/components/RoundAddButton/RoundAddButton.tsx
  src/features/schedules/components/RoundAddButton/index.ts
  src/features/schedules/components/RoundUserAddButton/RoundUserAddButton.tsx
  src/features/schedules/components/RoundUserAddButton/index.ts
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/schedules/components/Schedule/index.ts
  src/features/schedules/components/Schedules/Schedules.tsx
  src/features/schedules/components/Schedules/index.ts
  src/features/schedules/components/SearchPlace/SearchPlace.tsx
  src/features/schedules/components/SearchPlace/index.ts
  src/pages/schedules/ScheduleUpdatePage.tsx
  src/pages/schedules/SchedulesPage.tsx
  yarn.lock
Labels: ✨ Feature

#10 feat: 메모 및 투표 페이지 markup
  src/components/GoToBackButton/GoToBackButton.tsx
  src/components/GoToBackButton/index.ts
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/components/MemoContent/index.ts
  src/features/memo/components/MemoHeader/MemoHeader.tsx
  src/features/memo/components/MemoHeader/index.ts
  src/features/memo/components/MemoUpdateForm/MemoUpdateForm.tsx
  src/features/memo/components/MemoUpdateForm/index.ts
  src/features/memo/components/index.ts
  src/features/note/components/MemoThumbnail/MemoThumbnail.tsx
  src/features/note/components/MemoThumbnail/index.ts
  src/features/note/components/NoteTabs/NoteTabs.tsx
  src/features/note/components/NoteTabs/index.ts
  src/features/note/components/ThumbnailGrid/ThumbnailGrid.tsx
  src/features/note/components/ThumbnailGrid/index.ts
  src/features/note/components/VoteThumbnail/VoteThumbnail.tsx
  src/features/note/components/VoteThumbnail/index.ts
  src/features/note/components/index.ts
  src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
  src/features/vote/components/BodyAfterVote/index.ts
  src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
  src/features/vote/components/BodyBeforeVote/index.ts
  src/features/vote/components/VoteHeader/VoteHeader.tsx
  src/features/vote/components/VoteHeader/index.ts
  src/features/vote/components/VoteTitle/VoteTitle.tsx
  src/features/vote/components/VoteTitle/index.ts
  src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
  src/features/vote/components/VoteUpdateForm/index.ts
  src/features/vote/components/index.ts
  src/pages/memo/MemoPage.tsx
  src/pages/memo/MemoUpdatePage.tsx
  src/pages/note/NotePage.tsx
  src/pages/vote/VotePage.tsx
  src/pages/vote/VoteUpdatePage.tsx
  src/routes/memo/index.tsx
Labels: ✨ Feature

#12 feat: 마이페이지 markup
  src/components/ActionsMenu/ActionsMenu.tsx
  src/components/ActionsMenu/index.ts
  src/components/User/User.tsx
  src/components/User/index.ts
  src/features/posts/components/Post/Post.tsx
  src/pages/profile/ProfilePage.tsx
  src/utils/children.ts
Labels: ✨ Feature

#15 refactor: DatePicker 컴포넌트 리팩터링
  src/components/DatePicker/DatePicker.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
Labels: ✨ Feature

#17 feat: 로그인, 회원가입 폼에 react-hook-form 적용
  package.json
  src/features/auth/components/LoginForm/LoginForm.tsx
  src/features/auth/components/RegisterForm/RegisterForm.tsx
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  yarn.lock
Labels: ✨ Feature

#20 feat: 게시판(posts) 페이지 markup
  src/features/posts/components/Comment/Comment.tsx
  src/features/posts/components/Comment/index.ts
  src/features/posts/components/PostDetailContent/PostDetailContent.tsx
  src/features/posts/components/PostDetailContent/index.ts
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/posts/components/PostDetailHeader/index.ts
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/PostUpdateForm/index.ts
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/posts/components/SortBySelect/SortBySelect.tsx
  src/features/posts/components/index.ts
  src/pages/posts/PostPage.tsx
  src/pages/posts/PostUpdatePage.tsx
Labels: ✨ Feature

#19 feat: schedule 조회 페이지 마크업
  package.json
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/Carousel/Carousel.tsx
  src/features/schedules/components/Carousel/index.ts
  src/features/schedules/components/Daily/Daily.tsx
  src/features/schedules/components/DailyCarouselWithInfos/DailyCarouselWithInfos.tsx
  src/features/schedules/components/DailyCarouselWithInfos/index.ts
  src/features/schedules/components/Dailys/Dailys.tsx
  src/features/schedules/components/FriendsList/FriendsList.tsx
  src/features/schedules/components/ListWithVerticalLine/List.tsx
  src/features/schedules/components/ListWithVerticalLine/ListItem.tsx
  src/features/schedules/components/ListWithVerticalLine/ListWithVerticalLine.tsx
  src/features/schedules/components/ListWithVerticalLine/index.ts
  src/features/schedules/components/MapContainer/MapContainer.tsx
  src/pages/schedules/SchedulePage.tsx
  yarn.lock
Labels: ✨ Feature

#25 feat: proxy 경로 설정
  package.json
Labels: ✨ Feature

#30 feat: schedule 하위 페이지들 라우팅 연결
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/components/MemoHeader/MemoHeader.tsx
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
  src/features/vote/components/VoteHeader/VoteHeader.tsx
  src/pages/note/NotePage.tsx
  src/pages/schedules/SchedulePage.tsx
Labels: ✨ Feature

#31 fix: LinkOverLay를 Link 컴포넌트로 변경
  src/pages/note/NotePage.tsx
  src/pages/schedules/SchedulePage.tsx
Labels: 🔨 Refactor

#34 feat: AddScheduleForm 상태 값 react-hook-form으로 교체
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/Carousel/Carousel.tsx
  src/features/schedules/components/Daily/Daily.tsx
  src/features/schedules/components/Dailys/Dailys.tsx
  src/pages/schedules/SchedulesPage.tsx
  src/utils/date.ts
Labels: ✨ Feature

#33 feat: 메모 및 투표 페이지 공통컴포넌트 추가 및 react-hook-form 연결
  src/components/ActionsMenu/ActionsMenu.tsx
  src/components/GoToUpdateButton/GoToUpdateButton.tsx
  src/components/GoToUpdateButton/index.ts
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/components/MemoHeader/MemoHeader.tsx
  src/features/memo/components/MemoUpdateForm/MemoUpdateForm.tsx
  src/features/note/components/MemoThumbnail/MemoThumbnail.tsx
  src/features/note/components/NoteTabs/NoteTabs.tsx
  src/features/note/components/NoteTabs/index.ts
  src/features/note/components/ThumbnailGrid/ThumbnailGrid.tsx
  src/features/note/components/VoteThumbnail/VoteThumbnail.tsx
  src/features/note/components/index.ts
  src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
  src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
  src/features/vote/components/VoteHeader/VoteHeader.tsx
  src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
  src/pages/memo/MemoPage.tsx
  src/pages/memo/MemoUpdatePage.tsx
  src/pages/note/NotePage.tsx
  src/pages/vote/VotePage.tsx
  src/pages/vote/VoteUpdatePage.tsx
Labels: ✨ Feature

#40 feat: 2차 배포 추가 설정
  netlify.toml
Labels: 🌏 Deploy

#44 refactor: GoTo 버튼 리팩터링 및 반영
  src/components/GoToUpdateButton/GoToUpdateButton.tsx
  src/lib/axios.ts
  src/pages/note/NotePage.tsx
  src/pages/posts/PostUpdatePage.tsx
  src/pages/posts/PostsPage.tsx
  src/pages/schedules/ScheduleUpdatePage.tsx
  src/pages/schedules/SchedulesPage.tsx
Labels: 🔨 Refactor

#39 feat: schedule 생성 및 조회 페이지 react-query 연동
  src/components/Header/Header.tsx
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/Daily/Daily.tsx
  src/features/schedules/components/DailyCarouselWithInfos/DailyCarouselWithInfos.tsx
  src/features/schedules/components/Dailys/Dailys.tsx
  src/features/schedules/components/ListWithVerticalLine/ListWithVerticalLine.tsx
  src/features/schedules/components/MapContainer/MapContainer.tsx
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/ScheduleDetail/index.ts
  src/features/schedules/components/Schedules/Schedules.tsx
  src/features/schedules/components/SearchPlace/SearchPlace.tsx
  src/features/schedules/hooks/useScheduleData.ts
  src/features/schedules/types/index.ts
  src/pages/schedules/SchedulePage.tsx
  src/pages/schedules/SchedulesPage.tsx
  src/utils/date.ts
  yarn.lock
Labels: ✨ Feature

#46 feat: profile 및 posts 수정 코드 반영
  src/components/User/User.tsx
  src/features/auth/components/RegisterForm/RegisterForm.tsx
  src/features/auth/hooks/useAuthData.ts
  src/features/posts/components/LikedPosts/LikedPosts.tsx
  src/features/posts/components/LikedPosts/index.ts
  src/features/posts/components/MyPosts/MyPosts.tsx
  src/features/posts/components/MyPosts/index.ts
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/Posts/Posts.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/posts/components/SortBySelect/SortBySelect.tsx
  src/features/posts/components/index.ts
  src/features/posts/hooks/index.ts
  src/features/posts/hooks/usePostsData.ts
  src/features/posts/types/index.ts
  src/features/user/hooks/index.ts
  src/features/user/hooks/useUsersData.ts
  src/features/user/types/index.ts
  src/lib/react-query.ts
  src/pages/posts/PostsPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/utils/object.ts
  src/utils/types.ts
Labels: ✨ Feature

#47 feat: posts 생성, 조회, 댓글 추가 구현
  src/features/auth/components/RegisterForm/RegisterForm.tsx
  src/features/auth/types/index.ts
  src/features/posts/components/AddCommentForm/AddCommentForm.tsx
  src/features/posts/components/AddCommentForm/index.ts
  src/features/posts/components/Comment/Comment.tsx
  src/features/posts/components/Comments/Comments.tsx
  src/features/posts/components/Comments/index.ts
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostDetailContent/PostDetailContent.tsx
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/posts/components/PostLikeButton/PostLikeButton.tsx
  src/features/posts/components/PostLikeButton/index.ts
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/Posts/Posts.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/posts/components/SortBySelect/SortBySelect.tsx
  src/features/posts/components/index.ts
  src/features/posts/constants/index.ts
  src/features/posts/hooks/index.ts
  src/features/posts/hooks/useCommentsData.ts
  src/features/posts/hooks/usePostsData.ts
  src/features/posts/types/index.ts
  src/features/user/types/index.ts
  src/pages/posts/PostPage.tsx
  src/pages/posts/PostUpdatePage.tsx
  src/pages/posts/PostsPage.tsx
  src/utils/date.ts
  src/utils/object.ts
  src/utils/types.ts
Labels: ✨ Feature

#48 feat: 일정(schedule) 특정 및 공통 날짜 체크리스트 API 연결
  src/features/schedules/components/Checklist/Checklist.tsx
  src/features/schedules/components/Checklist/index.ts
  src/features/schedules/components/ChecklistForm/ChecklistForm.tsx
  src/features/schedules/components/ChecklistForm/index.ts
  src/features/schedules/components/CustomCheckBox/CustomCheckBox.tsx
  src/features/schedules/components/CustomCheckBox/index.ts
  src/features/schedules/components/DailyCarouselWithInfos/DailyCarouselWithInfos.tsx
  src/features/schedules/components/Dailys/Dailys.tsx
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/Schedules/Schedules.tsx
  src/features/schedules/components/ThemeTag/ThemeTag.tsx
  src/features/schedules/components/ThemeTag/index.ts
  src/features/schedules/hooks/useChecklistData.ts
  src/features/schedules/types/index.ts
  src/pages/schedules/SchedulePage.tsx
  src/pages/schedules/SchedulesPage.tsx
Labels: ✨ Feature

#55 fix: div상위 p태그
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
Labels: 🐞 BugFix

#57 fix: stylelint 순서 에러 처리 및 import 파일명 수정
  src/features/schedules/components/Checklist/Checklist.tsx
  src/features/schedules/components/CustomCheckBox/CustomCheckBox.tsx
  src/features/schedules/components/CustomCheckBox/index.ts
Labels: 🐞 BugFix

#51 feat: 투표 생성 react-query, note-page 스타일 수정
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/components/MemoUpdateForm/MemoUpdateForm.tsx
  src/features/memo/hooks/useMemoData.ts
  src/features/note/components/MemoList/MemoList.tsx
  src/features/note/components/VoteList/VoteList.tsx
  src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
  src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
  src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
  src/features/vote/hooks/useVoteData.ts
  src/pages/memo/MemoPage.tsx
  src/pages/memo/MemoUpdatePage.tsx
  src/pages/note/NotePage.tsx
  src/pages/vote/VotePage.tsx
Labels: ✨ Feature

#58 feat: posts 수정, 삭제 기능 추가
  src/App.tsx
  src/components/CustomSpinner/CustomSpinner.tsx
  src/components/CustomSpinner/index.ts
  src/components/Layout/PrivatePageLayout.tsx
  src/components/User/User.tsx
  src/features/auth/hooks/useAuthData.ts
  src/features/auth/types/index.ts
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/hooks/useMemoData.ts
  src/features/note/components/MemoList/MemoList.tsx
  src/features/note/hooks/useNoteData.ts
  src/features/posts/components/Comment/Comment.tsx
  src/features/posts/components/Comments/Comments.tsx
  src/features/posts/components/LikedPosts/LikedPosts.tsx
  src/features/posts/components/MyPosts/MyPosts.tsx
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/posts/constants/index.ts
  src/features/posts/hooks/useCommentsData.ts
  src/features/posts/hooks/usePostsData.ts
  src/features/posts/types/index.ts
  src/features/schedules/components/MapContainer/MapContainer.tsx
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/Schedules/Schedules.tsx
  src/features/schedules/components/ThemeTag/ThemeTag.tsx
  src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
  src/lib/axios.ts
  src/pages/posts/PostPage.tsx
  src/pages/posts/PostsPage.tsx
  src/pages/profile/ProfilePage.tsx
  src/pages/vote/VotePage.tsx
  src/routes/index.tsx
  src/utils/storage.ts
Labels: ✨ Feature

#61 hotfix: 회원가입 시 성별 타입 수정
  src/features/auth/components/RegisterForm/RegisterForm.tsx
  src/features/auth/types/index.ts
Labels: 🌏 Deploy, 🐞 BugFix

#64 fix: spotOrder 1부터 시작
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
Labels: 🐞 BugFix, 🔨 Doing

#65 fix: 일정(schedule) 낙관적 업데이트 관련 에러
  src/features/schedules/components/Checklist/Checklist.tsx
  src/features/schedules/components/CustomCheckBox/CustomCheckBox.tsx
  src/features/schedules/hooks/useChecklistData.ts
Labels: 🐞 BugFix

#70 refactor: 일정(Schedule) 타입 및 변경된 데이터 프로퍼티 정리
  src/features/schedules/components/AddSchedule/AddSchedule.tsx
  src/features/schedules/components/AddSchedule/index.ts
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/Checklist/Checklist.tsx
  src/features/schedules/components/DailyCarouselWithInfos/DailyCarouselWithInfos.tsx
  src/features/schedules/components/ListWithVerticalLine/ListWithVerticalLine.tsx
  src/features/schedules/components/MapContainer/MapContainer.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/SearchPlace/SearchPlace.tsx
  src/features/schedules/types/index.ts
  src/pages/schedules/ScheduleUpdatePage.tsx
Labels: 🔨 Refactor

#69 feat: 메모 및 투표 페이지 유저 정보와 액션버튼 조건부 렌더
  src/features/memo/components/MemoHeader/MemoHeader.tsx
  src/features/note/components/MemoList/MemoList.tsx
  src/features/vote/components/VoteHeader/VoteHeader.tsx
  src/pages/memo/MemoPage.tsx
  src/pages/memo/MemoUpdatePage.tsx
  src/pages/vote/VoteUpdatePage.tsx
Labels: ✨ Feature

#72 fix: 일정(schedule) react-query checklistId key 추가
  src/features/schedules/components/Checklist/Checklist.tsx
  src/features/schedules/hooks/useChecklistData.ts
Labels: 🐞 BugFix

#74 fix: 일정(schedule) 하루 당 최대 spot 제한 추가
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
Labels: 🐞 BugFix

#67 refactor: 공통 타입 추출 및 유틸 함수 반영
  src/features/auth/components/RegisterForm/RegisterForm.tsx
  src/features/auth/types/index.ts
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostDetailContent/PostDetailContent.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/Posts/Posts.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/posts/constants/index.ts
  src/features/posts/hooks/usePostsData.ts
  src/features/posts/types/index.ts
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/constants/index.ts
  src/features/user/components/FriendsList/FriendsList.tsx
  src/features/user/components/FriendsList/index.ts
  src/features/user/components/UserSearchForm/UserSearchForm.tsx
  src/features/user/components/UserSearchForm/index.ts
  src/features/user/constants/index.ts
  src/features/user/hooks/useUsersData.ts
  src/features/user/types/index.ts
  src/pages/profile/ProfilePage.tsx
  src/utils/date.ts
Labels: 🔨 Refactor

#76 fix: GoToBack 컴포넌트에 특정 페이지로 갈 수 있는 props 추가
  src/components/GoToBackButton/GoToBackButton.tsx
  src/pages/note/NotePage.tsx
  src/pages/schedules/SchedulePage.tsx
Labels: 🐞 BugFix

#78 fix: goToBack 버튼컴포넌트 navigate로 변경
  src/components/GoToBackButton/GoToBackButton.tsx
Labels: 🔨 Refactor

#79 feat: 도시 목록 API 연동 및 favicon 반영
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  src/features/posts/components/AddCommentForm/AddCommentForm.tsx
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/posts/components/PostLikeButton/PostLikeButton.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/Posts/Posts.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/posts/constants/index.ts
  src/features/posts/hooks/usePostsData.ts
  src/features/posts/types/index.ts
  src/features/user/components/FriendsList/FriendsList.tsx
  src/pages/posts/PostPage.tsx
  src/pages/schedules/SchedulePage.tsx
Labels: ✨ Feature

#82 fix: 일정 (Schedule) 체크리스트 validation 추가
  src/features/schedules/components/ChecklistForm/ChecklistForm.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
Labels: 🐞 BugFix

#77 feat: 일정(Schedule) 멤버 추가 기능 구현
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/FriendsList/FriendsList.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/hooks/useScheduleData.ts
  src/features/schedules/types/index.ts
Labels: ✨ Feature

#84 feat: 일정(schedule) 삭제 react-query 연동
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/Schedules/Schedules.tsx
  src/features/schedules/hooks/useScheduleData.ts
Labels: ✨ Feature

#83 feat: 게시글 관련 수정 사항 반영
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#85 최종 배포
  src/features/posts/components/Post/Post.tsx
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/ChecklistForm/ChecklistForm.tsx
  src/features/schedules/components/FriendsList/FriendsList.tsx
  src/features/schedules/components/Schedule/Schedule.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/Schedules/Schedules.tsx
  src/features/schedules/hooks/useScheduleData.ts
  src/features/schedules/types/index.ts
  src/routes/index.tsx
Labels: 🌏 Deploy

#86 hotfix: 게시글 본문 조회 및 수정 시 개행 반영
  src/features/posts/components/PostDetailContent/PostDetailContent.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/pages/posts/PostPage.tsx
Labels: 🐞 BugFix

#87 hotfix: 게시글 본문 조회 및 수정 시 개행 반영 (#86)
  src/features/posts/components/PostDetailContent/PostDetailContent.tsx
  src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
  src/pages/posts/PostPage.tsx
Labels: 🌏 Deploy

#88 hotfix: 투표 관련 렌더링 및 로직 이슈 수정
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/hooks/useMemoData.ts
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
  src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
  src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
  src/features/vote/hooks/useVoteData.ts
  src/pages/vote/VotePage.tsx
Labels: 🐞 BugFix

#89 hotfix: 투표 관련 렌더링 및 로직 이슈 수정 (#88)
  src/features/memo/components/MemoContent/MemoContent.tsx
  src/features/memo/hooks/useMemoData.ts
  src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
  src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
  src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
  src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
  src/features/vote/hooks/useVoteData.ts
  src/pages/vote/VotePage.tsx
Labels: 🐞 BugFix

#90 docs: README.md 작성
  README.md
Labels: 📃 Docs

#92 feat: API 서버 경로 변경
  netlify.toml
  package.json
Labels: 🌏 Deploy

#93 최종 배포 서버 URL 변경
  README.md
  netlify.toml
  package.json
Labels: 🌏 Deploy

#94 feat: 일정(Schedule) 수정 기능 구현
  src/features/schedules/components/AddSchleduleForm/AddScheduleForm.tsx
  src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
  src/features/schedules/components/SearchPlace/SearchPlace.tsx
  src/features/schedules/hooks/useScheduleData.ts
  src/features/schedules/types/index.ts
  src/pages/schedules/ScheduleUpdatePage.tsx
Labels: ✨ Feature
